language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.1


gemfile:
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
